"""Pydantic models for Graph RAG data structures.

Defines the core data models for graph-based legal document analysis:
- GraphNode: Entities (Parties, Sections, Obligations, etc.)
- GraphEdge: Relations between entities with evidence
- Evidence: Source attribution for relations
- GraphExtractionResult: Container for extraction output
"""

from typing import Any, Literal

from pydantic import BaseModel, Field


class Evidence(BaseModel):
    """Evidence linking an edge to source text in a chunk.

    Every edge MUST have at least one evidence entry. Edges without
    evidence are dropped and not persisted to the database.

    Attributes:
        document_id: UUID of the source document
        chunk_index: Index of the chunk containing the evidence
        page: Page number if available from chunk metadata
        start_char: Character offset start in the chunk
        end_char: Character offset end in the chunk
        snippet: Text snippet (quote) supporting the relation
    """

    document_id: str = Field(..., description="Source document UUID")
    chunk_index: int = Field(..., ge=0, description="Chunk index containing evidence")
    page: int | None = Field(default=None, description="Page number if available")
    start_char: int | None = Field(
        default=None, description="Character offset start in chunk"
    )
    end_char: int | None = Field(
        default=None, description="Character offset end in chunk"
    )
    snippet: str = Field(
        ..., min_length=1, description="Text snippet supporting the relation"
    )


class GraphNode(BaseModel):
    """A node in the legal knowledge graph representing an entity.

    Nodes are scoped per document and user for RLS enforcement.

    Attributes:
        id: UUID primary key (auto-generated by DB if not provided)
        document_id: UUID of the source document
        user_id: User ID for RLS isolation
        node_type: Category of entity (Party, Section, Obligation, etc.)
        label: Display name for the node
        properties: Additional attributes as JSONB
    """

    id: str | None = Field(
        default=None, description="UUID primary key (auto-generated by DB)"
    )
    document_id: str = Field(..., description="Source document UUID")
    user_id: str = Field(..., description="RLS user identifier")
    node_type: Literal[
        "Document",
        "Section",
        "Party",
        "Obligation",
        "Deadline",
        "Amount",
        "Penalty",
        "Definition",
        "Reference",
    ] = Field(..., description="Entity category")
    label: str = Field(..., min_length=1, description="Display name")
    properties: dict[str, Any] = Field(
        default_factory=dict, description="Additional JSONB attributes"
    )

    def to_db_dict(self) -> dict[str, Any]:
        """Convert to dictionary for database insertion.

        Excludes the id field which is auto-generated by the database.
        """
        return self.model_dump(exclude={"id"}, exclude_none=True)


class GraphEdge(BaseModel):
    """An edge in the legal knowledge graph representing a relation.

    Edges connect two nodes and MUST include evidence pointing back
    to the source text. Edges without evidence are dropped.

    Attributes:
        id: UUID primary key (auto-generated by DB if not provided)
        document_id: UUID of the source document
        user_id: User ID for RLS isolation
        source_node_id: UUID of the source node
        target_node_id: UUID of the target node
        edge_type: Category of relation (OBLIGATES, REFERENCES, etc.)
        evidence: Required evidence for this edge
    """

    id: str | None = Field(
        default=None, description="UUID primary key (auto-generated by DB)"
    )
    document_id: str = Field(..., description="Source document UUID")
    user_id: str = Field(..., description="RLS user identifier")
    source_node_id: str = Field(..., description="UUID of source node")
    target_node_id: str = Field(..., description="UUID of target node")
    edge_type: Literal[
        "OBLIGATES",
        "HAS_DEADLINE",
        "HAS_AMOUNT",
        "HAS_PENALTY",
        "DEFINES",
        "REFERENCES",
        "EXCEPTION_OF",
    ] = Field(..., description="Relation category")
    evidence: Evidence = Field(
        ..., description="Required evidence (edges without evidence are dropped)"
    )

    def to_db_dict(self) -> dict[str, Any]:
        """Convert to dictionary for database insertion.

        Excludes the id field and converts evidence to dict for JSONB storage.
        """
        data = self.model_dump(exclude={"id"}, exclude_none=True)
        data["evidence"] = self.evidence.model_dump()
        return data


class GraphExtractionResult(BaseModel):
    """Result of graph extraction from document chunks.

    Container for all nodes and edges extracted from a document.
    Used as the return type for GraphExtractor.extract().

    Attributes:
        document_id: UUID of the processed document
        user_id: User ID for RLS
        nodes: List of extracted nodes
        edges: List of extracted edges (all have evidence)
        statistics: Extraction statistics (counts, durations, etc.)
    """

    document_id: str = Field(..., description="Processed document UUID")
    user_id: str = Field(..., description="RLS user identifier")
    nodes: list[GraphNode] = Field(default_factory=list, description="Extracted nodes")
    edges: list[GraphEdge] = Field(
        default_factory=list, description="Extracted edges (all have evidence)"
    )
    statistics: dict[str, Any] = Field(
        default_factory=dict,
        description="Extraction stats: node_count, edge_count, duration_ms, etc.",
    )

    def get_nodes_by_type(
        self, node_type: str
    ) -> list[GraphNode]:
        """Get all nodes of a specific type.

        Args:
            node_type: The node type to filter by

        Returns:
            List of matching nodes
        """
        return [n for n in self.nodes if n.node_type == node_type]

    def get_edges_by_type(
        self, edge_type: str
    ) -> list[GraphEdge]:
        """Get all edges of a specific type.

        Args:
            edge_type: The edge type to filter by

        Returns:
            List of matching edges
        """
        return [e for e in self.edges if e.edge_type == edge_type]
