"""Database repository layer for document ingestion.

Provides type-safe repository classes for documents and chunks with
RLS-aware operations via SupabaseClient.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field

from services.storage.supabase_client import DatabaseError, SupabaseClient

logger = logging.getLogger(__name__)


# =============================================================================
# Pydantic Models for Type Safety
# =============================================================================


class DocumentCreate(BaseModel):
    """Input model for creating a new document record."""

    user_id: str = Field(..., description="RLS user identifier")
    filename: str = Field(..., description="Original filename")
    file_type: Literal["pdf", "docx", "xlsx"] = Field(
        ..., description="Document type"
    )
    file_size: int = Field(..., ge=0, description="File size in bytes")
    storage_path: str = Field(
        ..., description="Path in Supabase Storage: {user_id}/{document_id}/{filename}"
    )
    status: Literal["processing", "ready", "failed"] = Field(
        default="processing", description="Current processing status"
    )
    error_msg: str | None = Field(default=None, description="Error message if failed")
    meta: dict[str, Any] = Field(
        default_factory=dict, description="JSONB metadata (XLSX info, graph status)"
    )


class DocumentRecord(BaseModel):
    """Complete document record as stored in the database."""

    id: str = Field(..., description="UUID primary key")
    user_id: str = Field(..., description="RLS user identifier")
    filename: str = Field(..., description="Original filename")
    file_type: Literal["pdf", "docx", "xlsx"] = Field(..., description="Document type")
    file_size: int = Field(..., ge=0, description="File size in bytes")
    storage_path: str = Field(..., description="Path in Supabase Storage")
    status: Literal["processing", "ready", "failed"] = Field(
        ..., description="Current processing status"
    )
    error_msg: str | None = Field(
        default=None, description="Error message if processing failed"
    )
    meta: dict[str, Any] = Field(
        default_factory=dict, description="JSONB metadata"
    )
    created_at: datetime = Field(..., description="Record creation timestamp")
    updated_at: datetime = Field(..., description="Last update timestamp")

    @classmethod
    def from_db_row(cls, row: dict[str, Any]) -> DocumentRecord:
        """Create a DocumentRecord from a database row dictionary.

        Handles datetime parsing from ISO format strings.
        """
        data = dict(row)

    
        for field in ["created_at", "updated_at"]:
            if field in data and isinstance(data[field], str):
                data[field] = datetime.fromisoformat(
                    data[field].replace("Z", "+00:00")
                )

        return cls(**data)


class ChunkRecord(BaseModel):
    """Chunk record as stored in the database with embeddings."""

    id: str | None = Field(
        default=None, description="UUID primary key (auto-generated by DB)"
    )
    document_id: str = Field(..., description="FK to documents table")
    user_id: str = Field(..., description="RLS user identifier")
    chunk_index: int = Field(..., ge=0, description="Sequential index within document")
    content: str = Field(..., description="Chunk text content")
    embedding: list[float] | None = Field(
        default=None, description="1536-dim OpenAI embedding vector"
    )
    section_hint: str | None = Field(
        default=None, description="Detected heading (e.g., 'Clause 12', 'Art. 5')"
    )
    section_path: list[str] = Field(
        default_factory=list, description="Hierarchy breadcrumbs"
    )
    page_start: int | None = Field(default=None, description="Starting page number")
    page_end: int | None = Field(default=None, description="Ending page number")
    anchors: list[str] = Field(
        default_factory=list, description="Detected references in text"
    )
    char_start: int = Field(..., ge=0, description="Start character offset")
    char_end: int = Field(..., ge=0, description="End character offset")
    created_at: datetime | None = Field(
        default=None, description="Record creation timestamp"
    )

    def to_db_dict(self) -> dict[str, Any]:
        """Convert to dictionary for database insertion.

        Excludes auto-generated fields (id, created_at) and handles
        the embedding vector format for pgvector.
        """
        data = self.model_dump(
            exclude={"id", "created_at"},
            exclude_none=False,
        )

   
        data["section_path"] = list(self.section_path) if self.section_path else []
        data["anchors"] = list(self.anchors) if self.anchors else []

      
        if self.embedding is not None:
            data["embedding"] = self.embedding
        else:
            data.pop("embedding", None)

        return data

    @classmethod
    def from_db_row(cls, row: dict[str, Any]) -> ChunkRecord:
        """Create a ChunkRecord from a database row dictionary."""
        data = dict(row)

       
        if "created_at" in data and isinstance(data["created_at"], str):
            data["created_at"] = datetime.fromisoformat(
                data["created_at"].replace("Z", "+00:00")
            )

     
        for field in ["section_path", "anchors"]:
            if field in data and data[field] is None:
                data[field] = []

        return cls(**data)


# =============================================================================
# Repository Classes
# =============================================================================


class DocumentRepository:
    """Repository for document records with RLS-aware operations.

    All methods enforce user_id filtering to maintain row-level security.
    Uses SupabaseClient for database operations.
    """

    def __init__(self, client: SupabaseClient) -> None:
        """Initialize with a SupabaseClient instance.

        Args:
            client: Configured SupabaseClient for database operations.
        """
        self._client = client

    async def create(self, document: DocumentCreate) -> DocumentRecord:
        """Create a new document record.

        Args:
            document: Document creation data including user_id and file info.

        Returns:
            The created DocumentRecord with generated id and timestamps.

        Raises:
            DatabaseError: If insert fails or violates constraints.
        """
        try:
            data = document.model_dump()
            result = await self._client.insert(
                table_name="documents",
                data=data,
                user_id=document.user_id,
            )

            if not result.data:
                raise DatabaseError("Insert succeeded but no data returned")

            record = DocumentRecord.from_db_row(result.data[0])
            logger.info(
                "Created document record: %s for user: %s",
                record.id,
                record.user_id,
            )
            return record

        except DatabaseError:
            raise
        except Exception as e:
            logger.exception("Failed to create document record")
            raise DatabaseError(f"Failed to create document: {e}", e) from e

    async def get_by_id(
        self, document_id: str, user_id: str
    ) -> DocumentRecord | None:
        """Retrieve a document by ID with user_id verification.

        Args:
            document_id: UUID of the document to retrieve.
            user_id: User ID for RLS filtering (must match document owner).

        Returns:
            DocumentRecord if found, None if not found or user mismatch.

        Raises:
            DatabaseError: If query fails.
        """
        try:
            result = await self._client.select(
                table_name="documents",
                user_id=user_id,
                filters={"id": document_id},
                limit=1,
            )

            if not result.data:
                return None

            return DocumentRecord.from_db_row(result.data[0])

        except DatabaseError:
            raise
        except Exception as e:
            logger.exception("Failed to get document by id: %s", document_id)
            raise DatabaseError(
                f"Failed to get document {document_id}: {e}", e
            ) from e

    async def update_status(
        self,
        document_id: str,
        status: Literal["processing", "ready", "failed"],
        error_msg: str | None = None,
        user_id: str | None = None,
    ) -> DocumentRecord:
        """Update the status of a document.

        Args:
            document_id: UUID of the document to update.
            status: New status value.
            error_msg: Optional error message for failed status.
            user_id: User ID for RLS filtering. Required for security.

        Returns:
            The updated DocumentRecord.

        Raises:
            DatabaseError: If update fails or document not found.
        """
        if not user_id:
            raise DatabaseError(
                "user_id is required for update_status to enforce RLS"
            )

        try:
            update_data: dict[str, Any] = {"status": status}
            if error_msg is not None:
                update_data["error_msg"] = error_msg

            result = await self._client.update(
                table_name="documents",
                data=update_data,
                user_id=user_id,
                filters={"id": document_id},
            )

            if not result.data:
                raise DatabaseError(
                    f"Document not found or access denied: {document_id}"
                )

            record = DocumentRecord.from_db_row(result.data[0])
            logger.info(
                "Updated document %s status to: %s",
                document_id,
                status,
            )
            return record

        except DatabaseError:
            raise
        except Exception as e:
            logger.exception("Failed to update document status: %s", document_id)
            raise DatabaseError(
                f"Failed to update status for {document_id}: {e}", e
            ) from e

    async def list_by_user(
        self,
        user_id: str,
        status: Literal["processing", "ready", "failed"] | None = None,
    ) -> list[DocumentRecord]:
        """List all documents for a user with optional status filter.

        Args:
            user_id: User ID to filter by (RLS enforcement).
            status: Optional status filter.

        Returns:
            List of DocumentRecord matching the criteria.

        Raises:
            DatabaseError: If query fails.
        """
        try:
            filters: dict[str, Any] = {}
            if status:
                filters["status"] = status

            result = await self._client.select(
                table_name="documents",
                user_id=user_id,
                filters=filters if filters else None,
                order_by=("created_at", "desc"),
            )

            records = [DocumentRecord.from_db_row(row) for row in result.data]
            logger.debug(
                "Listed %d documents for user: %s (status filter: %s)",
                len(records),
                user_id,
                status or "none",
            )
            return records

        except DatabaseError:
            raise
        except Exception as e:
            logger.exception("Failed to list documents for user: %s", user_id)
            raise DatabaseError(f"Failed to list documents: {e}", e) from e

    async def delete(self, document_id: str, user_id: str) -> bool:
        """Delete a document record.

        Args:
            document_id: UUID of the document to delete.
            user_id: User ID for RLS filtering (must be owner).

        Returns:
            True if deleted, False if not found.

        Raises:
            DatabaseError: If delete fails.
        """
        try:
            result = await self._client.delete(
                table_name="documents",
                user_id=user_id,
                filters={"id": document_id},
            )

            deleted = len(result.data) > 0
            if deleted:
                logger.info("Deleted document: %s", document_id)
            else:
                logger.warning("Document not found for deletion: %s", document_id)

            return deleted

        except DatabaseError:
            raise
        except Exception as e:
            logger.exception("Failed to delete document: %s", document_id)
            raise DatabaseError(
                f"Failed to delete document {document_id}: {e}", e
            ) from e


class ChunkRepository:
    """Repository for chunk records with batch operations and RLS awareness.

    Provides efficient batch upsert for embedding storage and retrieval
    by document with user_id verification.
    """

    def __init__(self, client: SupabaseClient) -> None:
        """Initialize with a SupabaseClient instance.

        Args:
            client: Configured SupabaseClient for database operations.
        """
        self._client = client

    async def upsert_chunks(self, chunks: list[ChunkRecord]) -> list[ChunkRecord]:
        """Batch upsert chunks into the database.

        Uses ON CONFLICT (document_id, chunk_index) DO UPDATE for idempotency.
        All chunks must have the same user_id (enforced for RLS).

        Args:
            chunks: List of ChunkRecord to upsert. Must include user_id.

        Returns:
            List of upserted ChunkRecord with generated IDs.

        Raises:
            DatabaseError: If upsert fails or chunks have mixed user_ids.
            ValueError: If chunks list is empty.
        """
        if not chunks:
            raise ValueError("Cannot upsert empty chunk list")

      
        for chunk in chunks:
            if not chunk.user_id:
                raise DatabaseError(
                    "All chunks must have user_id for RLS compliance"
                )

      
        user_ids = {chunk.user_id for chunk in chunks}
        if len(user_ids) > 1:
            raise DatabaseError(
                f"Batch upsert requires consistent user_id, got: {user_ids}"
            )

        user_id = chunks[0].user_id

        try:
           
            data = [chunk.to_db_dict() for chunk in chunks]

            result = await self._client.upsert(
                table_name="chunks",
                data=data,
                on_conflict="document_id,chunk_index",
                user_id=user_id,
            )

            if not result.data:
               
                logger.warning("Upsert returned no data, chunks may still be stored")
                return chunks

            records = [ChunkRecord.from_db_row(row) for row in result.data]
            logger.info(
                "Upserted %d chunks for document: %s",
                len(records),
                chunks[0].document_id,
            )
            return records

        except DatabaseError:
            raise
        except Exception as e:
            logger.exception("Failed to upsert chunks")
            raise DatabaseError(f"Failed to upsert chunks: {e}", e) from e

    async def get_by_document(
        self, document_id: str, user_id: str
    ) -> list[ChunkRecord]:
        """Retrieve all chunks for a specific document.

        Args:
            document_id: UUID of the document.
            user_id: User ID for RLS filtering (must match document owner).

        Returns:
            List of ChunkRecord ordered by chunk_index.

        Raises:
            DatabaseError: If query fails.
        """
        try:
            result = await self._client.select(
                table_name="chunks",
                user_id=user_id,
                filters={"document_id": document_id},
                order_by=("chunk_index", "asc"),
            )

            records = [ChunkRecord.from_db_row(row) for row in result.data]
            logger.debug(
                "Retrieved %d chunks for document: %s",
                len(records),
                document_id,
            )
            return records

        except DatabaseError:
            raise
        except Exception as e:
            logger.exception(
                "Failed to get chunks for document: %s", document_id
            )
            raise DatabaseError(
                f"Failed to get chunks for {document_id}: {e}", e
            ) from e

    async def delete_by_document(self, document_id: str, user_id: str) -> int:
        """Delete all chunks for a specific document.

        Used when reprocessing or deleting a document.

        Args:
            document_id: UUID of the document.
            user_id: User ID for RLS filtering.

        Returns:
            Number of chunks deleted.

        Raises:
            DatabaseError: If delete fails.
        """
        try:
            result = await self._client.delete(
                table_name="chunks",
                user_id=user_id,
                filters={"document_id": document_id},
            )

            count = len(result.data)
            logger.info(
                "Deleted %d chunks for document: %s",
                count,
                document_id,
            )
            return count

        except DatabaseError:
            raise
        except Exception as e:
            logger.exception(
                "Failed to delete chunks for document: %s", document_id
            )
            raise DatabaseError(
                f"Failed to delete chunks for {document_id}: {e}", e
            ) from e


__all__ = [
    "DocumentCreate",
    "DocumentRecord",
    "ChunkRecord",
    "DocumentRepository",
    "ChunkRepository",
]
